title: "Ioana Leuştean"
description: >
  Professor <br>
  Faculty of Mathematics and Computer Science <br>
  University of Bucharest, Romania

theme: minima

# Setări opționale pentru Minima
header_pages:
  - index.md
  - teaching.md
  - publications.md

